version: '3.7'

services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000 --settings=${SETTING_PATH}
        volumes:
            - .:/pass-the-key
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
volumes:
    postgres_data: